### ISSUE TITLE
Small Outdated Information Note

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [YouHaveTrouble/minecraft-optimization#100]
First of all, excellent guide. Thank you. Saves me time of having to write all this information when teaching people how to make an MC server. Instead I can just link them your guide.

Secondly, on [this](https://github.com/YouHaveTrouble/minecraft-optimization/wiki/Common-pitfalls-and-best-practices) page I noticed it mentions using [tuinity](https://ci.codemc.io/job/Spottedleaf/job/Tuinity). That server software has been merged into Paper and thus should be removed as a suggestion. 

Please Note: I do not check Github regularly and thus will likely not see replies.

**Comment by YouHaveTrouble** [comment]
Tuinity reference removed. Thanks for pointing this out!
