### ISSUE TITLE
Add --add-modules=jdk.incubator.vector to the guide

### ISSUE THREAD

**Issue by Huge-mistake** [YouHaveTrouble/minecraft-optimization#105]
https://github.com/YouHaveTrouble/minecraft-optimization/discussions/71
Add to the startup flags section. It enables feature's in Pufferfish:
It uses SIMD instructions on your CPU, making some math faster (Only used for map rendering at this moment).

**Comment by YouHaveTrouble** [comment]
[It's already there](https://github.com/YouHaveTrouble/minecraft-optimization/blob/1.20/README.md?plain=1#L574)
