### ISSUE TITLE
entity-broadcast-range-percentage

### ISSUE THREAD

**Issue by ColorsASD** [YouHaveTrouble/minecraft-optimization#113]
On my server, due to the multitude of unique items, users have consistently experienced low FPS levels. While elsewhere they might have around 100-120 FPS, in my lobby, for example, it's around 50-60. You could try adjusting the "entity-broadcast-range-percentage" setting similarly to the "entity-tracking-range" setting. However, this setting affects everything that could cause lag and may also benefit those with poor internet connections. Here are a few visual examples with a value of 20:

![image](https://github.com/YouHaveTrouble/minecraft-optimization/assets/12263156/e6933041-da81-4d17-ac90-08b71c5b9fe2)
![image](https://github.com/YouHaveTrouble/minecraft-optimization/assets/12263156/aebbb24e-30e2-49bc-8785-6c669d6cce1b)

entity-broadcast-range-percentage=100 (63-65 FPS):
![image](https://github.com/YouHaveTrouble/minecraft-optimization/assets/12263156/78cc32b2-4c7d-4fbc-b275-545a642c0e23)

entity-broadcast-range-percentage=20: (74-78 FPS):
![image](https://github.com/YouHaveTrouble/minecraft-optimization/assets/12263156/b392ece5-3839-40ee-b93d-1d4ee402dc3b)

**Comment by ColorsASD** [comment]
My request/suggestion would be only to explore, with your settings, how and to what extent this setting could be connected to your preferences, so that they do not cause any conflicts.

**Comment by YouHaveTrouble** [comment]
As this is not really a server optimization matter, I'm gonna convert this to a discussion. This is still relevant for some, but generally if you have fps issues due to amount of entities, you probably have way too many entities.
