### ISSUE TITLE
1.20.4 grass renamed to short_grass

### ISSUE THREAD

**Issue by AndrewDragonCh** [YouHaveTrouble/minecraft-optimization#116]
If you follow this guide you'll get this error:

`[Server thread/ERROR]: [MapSerializer] Could not deserialize key grass into class net.minecraft.world.item.Item at [entities, spawning, alt-item-despawn-rate, items]`

This is due to the renaming of grass to short_grass (why??) Just thought I'd give a heads up.

**Comment by YouHaveTrouble** [comment]
> grass to short_grass (why??)

Probably because some mojang dev /filled an area with the grass plant instead of grass block ;P
Anyway, updated the list
