### ISSUE TITLE
treasure-maps "Describe the modification"

### ISSUE THREAD

**Issue by CatTeaA** [YouHaveTrouble/minecraft-optimization#125]
Starting from version 1.20.5, the treasure map seems not to cause server lag or freezing.

Perhaps a prompt for this piece of information could be added

https://bugs.mojang.com/browse/MC-249136

**Comment by YouHaveTrouble** [comment]
Patch notes denoted that the issue was not fixed completely, but its effects were greatly reduced. There can still be situations where the lookup will take longer than expected.
