### ISSUE TITLE
Could I translate this to Chinese?

### ISSUE THREAD

**Issue by Mhy278** [YouHaveTrouble/minecraft-optimization#25]
Hello,
I am a minecraft player and also a developer who come from China. I think compared with the traditional, your guide gives more detailed introduction to the configuration. It is flabbergasted to let the server owner make his own choice and gradually adjust the configuration,this is a great innovation and inspired me a lot!
So, could you allow me to translate this guide into Chinese and publish it on MCBBS,which is the most prestigious forum and I can also pull request to this repository at the same time?

**Comment by YouHaveTrouble** [comment]
Translate it, sure, the more people information can reach, the better. Just please link to the original guide if you do post it somewhere :)

Not sure about PR here, since I don't speak chinese it would be a bother to maintain and update multiple language versions.

**Comment by Mhy278** [comment]
Thank you very much,I will do it.

**Comment by Rabbit0w0** [comment]
Where is your translation? Dropped??

**Comment by Mhy278** [comment]
> Where is your translation? Dropped??
> 
> Close this issue if you even don't want to do that.

nop,here it is: https://github.com/Mhy278/MinecraftServerHostGuide/blob/master/Optimization.md

**Comment by Rabbit0w0** [comment]
Consider to post it to Gist or Chinese platforms Github isn't a right choice

**Comment by Mhy278** [comment]
> Consider to post it to Gist or Chinese platforms Github isn't a right choice

you are right,so here it is: https://www.mcbbs.net/thread-1199027-1-1.html

**Comment by YouHaveTrouble** [comment]
for any questions about translations from this point, refer to #42
