### ISSUE TITLE
suggestion: add to the guide viewdistancetweaks

### ISSUE THREAD

**Issue by gabboman** [YouHaveTrouble/minecraft-optimization#43]
[https://www.spigotmc.org/resources/view-distance-tweaks-1-14-1-17.75164/](https://www.spigotmc.org/resources/view-distance-tweaks-1-14-1-17.75164/)

Imagine for a moment that the server changed the simulation distance and the view distance (view-distance & no-tick-view-distance) depending on how many active players there are  and if the tps go up and down it acts accordingly.

Imagine: 2 players on a 16gb ram machine with a modern i7? HELL YEAH BABY, YOU CAN WATCH 32 CHUNKS and the server ticks let's say a distance of 16

oh shit, suddenly pewdiepie joined and all his fans joined too! we have 200 people online! Well, time to optimize: you can see 8 chunks and the server is ticking like 4.

lag? minimum

now stop imagining all that. this plugin with the apropiate configuration can do it.

What i mean is that you might want to add this to the guide because its a great tool.

I hope I could do soemthing slightly useful for your guide.

Regards

**Comment by YouHaveTrouble** [comment]
I am not a fan of this solution, all it does is creates inconsistency in gameplay. It's not really better than just setting no-tick-view-distance to desired value and keeping ticking distance the same and low at all times.
Additionally, you can't control mob spawn ranges and mob despawn ranges along with the view distances.

Overall, you're better off setting basic configs than letting plugins "optimize"
