### ISSUE TITLE
License repo under a free license

### ISSUE THREAD

**Issue by fredster33** [YouHaveTrouble/minecraft-optimization#54]

**Comment by YouHaveTrouble** [comment]
I don't see any benefit this would bring.

**Comment by fredster33** [comment]
It allows people to actually use the advice here freely, and also gives protections to contributors so we can't get sued one day.

**Comment by YouHaveTrouble** [comment]
You won't get sued. The guide is on github for sole reason for people to contribute. If I didn't grant you permission to modify it I would not accept pull requests.

I will not license the guide under free license for several reasons:
- free licenses allow for commercial use. I don't want to ever see someone hiding information from this guide behind a paywall.
- free license would allow people to use this guide without context or explanation, which misses the point
- copies that would inevitably been made and stopped updating could be harmful for the users

**Comment by fredster33** [comment]
Got it.
