### ISSUE TITLE
Suggestion: Nether no-tick-view-distance

### ISSUE THREAD

**Issue by Pantera07** [YouHaveTrouble/minecraft-optimization#57]
I think it would be better to reduce or disable 'no-tick-view-distance' in 'world_nether'.
In the Nether, you can't see far in the fog.

**Comment by Pantera07** [comment]
world_nether:
    viewdistances:
      no-tick-view-distance: -1

**Comment by YouHaveTrouble** [comment]
The guide focuses on optimization, not visuals.

You're free to use whatever settings you want, guide should just be starting point.

**Comment by Pantera07** [comment]
> The guide focuses on optimization, not visuals.
> 
> You're free to use whatever settings you want, guide should just be starting point.

I think you can optimize by reducing no-tick-view-distance.

**Comment by YouHaveTrouble** [comment]
> > The guide focuses on optimization, not visuals.
> > You're free to use whatever settings you want, guide should just be starting point.
> 
> I think you can optimize by reducing no-tick-view-distance.

Read the name of the option again.

It's view distance for chunks that *do not tick*. Therefore they barely use any cpu and only a bit of disk IO.
You will not get significant performance gains out of reducing them in 99.9% of cases.

**Comment by Pantera07** [comment]
> > > The guide focuses on optimization, not visuals.
> > > You're free to use whatever settings you want, guide should just be starting point.
> > 
> > 
> > I think you can optimize by reducing no-tick-view-distance.
> 
> Read the name of the option again.
> 
> It's view distance for chunks that _do not tick_. Therefore they barely use any cpu and only a bit of disk IO.
> You will not get significant performance gains out of reducing them in 99.9% of cases.

I think no-tick-view-distance also does chunk generate.
chunk generate causes lag

**Comment by YouHaveTrouble** [comment]
I think you might have [missed a step](https://github.com/YouHaveTrouble/minecraft-optimization#map-pregen).
