### ISSUE TITLE
Wrong statements about Mohist

### ISSUE THREAD

**Issue by CraftJunkies** [YouHaveTrouble/minecraft-optimization#60]
Please correct your sayings about mohist. Its completly open source and no maliscius software. If you believe such false rumors, please take this git down. Here is more about the rumors stated: https://discord.com/channels/311256119005937665/550911071188418571/912420621835731024

> :emoji_2: Hello everyone, i see a lot of people saying Mohist is malicious because of the EssentialsX PSA published a few months ago about Mohist. Of couse, Mohist is not malicious, and i even wrote an article about it. 

>Please know that almost all (and maybe all) of the information of that PSA is false and outdated.

>Of course, we do not replace plugins jar by malicious jars, since all of them are free and open source on GitHub since the begenning, and you can find the modified EssentialsX repository which contains all of the source code here https://github.com/KR33PY/Essentials. That's why I highly recommend everyone who read the PSA to read this https://github.com/Shawiizz/MohistEssentialsX/blob/main/README.md to understand why you shouldn't trust the content of the EssentialsX PSA.

>By the way, know that the Mohist plugin checker always ask your permission before downloading a plugin, and you can even disable it in the mohist.yml confirguration file (disable_plugins_blacklist option) and it has always been the case since the creation of this plugin checker. It even gives you the url of the GitHub repository so that you can check the source code easily. We don't really understand the behavior of EssentialsX team, and we still don't know exactly why this PSA has been written.

>To finish, please do not trust everyone! As you can see, a lot of false information can be wrote about something, and in this case, the EssentialsX team wrote a lot of false information about the Mohist project and about our team, while they do not know anything about it and the consequences that this could have on the Mohist project.

>Thanks for reading, and I hope this announcement will make some people know the truth about this subject.
The Mohist Team 

Here the full explanation https://github.com/Shawiizz/MohistEssentialsX/blob/main/README.md

**Comment by YouHaveTrouble** [comment]
1. All things I mention in the guide are generally accepted by the most of the community as truth.
2. Mohist has been and still is shady af.
3. You can't expect anyone to take a project seriously when they [try to turn the warning aganist them into an ad](https://github.com/EssentialsX/Website/pull/44/commits/02b80afa4603bf46ecedb38d56b29428013922ad)
4. Playing the victim and "it's hard to do" is not an argument to counter anything.
5. "Mohist is not malicious ~The Mohist Team"

> If you believe such false rumors, please take this git down

you wish.

**Comment by Shawiizz** [comment]
You're free to say Mohist is not good, but you can't say it's malicious when everything is open source and that you can check the source code yourself. Mohist is open source and modified plugins are also open source, and everyone can check the source code and see that nothing is malicious. EssentialsX is lying to its community and that's a shame, and you also can't take a project that lies to its community seriously.

**Comment by partydev** [comment]
> You're free to say Mohist is not good, but you can't say it's malicious when everything is open source and that you can check the source code yourself. Mohist is open source and modified plugins are also open source, and everyone can check the source code and see that nothing is malicious. EssentialsX is lying to its community and that's a shame, and you also can't take a project that lies to its community seriously.

They are not lying... just because you stopped doing something bad does not mean you did not do something bad.

**Comment by Shawiizz** [comment]
They still say Mohist is malicious while it have never been malicious, that's why I say they're lying. And the EssentialsX fork made by Mohist's developers has always been on GitHub and I don't see anything bad in forking a spigot plugin.

**Comment by Encode42** [comment]
$NO, final offer
