### ISSUE TITLE
impact

### ISSUE THREAD

**Issue by ZConnorZ** [YouHaveTrouble/minecraft-optimization#67]
You can specify the degree of impact of the configuration on performance using tags.
For example:
view-distance | Impact: **Heavy**

**Comment by YouHaveTrouble** [comment]
Not gonna happen, impact from every feature is a variable.

view-distance might not be any issue for one server with okay networking and storage speed, but completely kill chunk loading for everyone on a budget server.

Hoppers might not be an issue at all on some servers, on some others there could be some crazies that put 10k hoppers in 1 chunk and it kills the server.

There is no black and white, there's only a lot of grey.
