### ISSUE TITLE
The Airplane is recommended server software?

### ISSUE THREAD

**Issue by andris155** [YouHaveTrouble/minecraft-optimization#7]
This fork includes optimizations oriented towards large servers.
https://github.com/TECHNOVE/Airplane

**Comment by YouHaveTrouble** [comment]
Airplane is fairly new fork and I can't recommend anything that wasn't yet throughly tested by the community, and more importantly, time.

If airplane sticks around and proves itself to be stable I will add it to the guide. If you're asking for yourself, you're free to test it out and see for yourself. If you feel like it's good enough for you, then go for it.
