### ISSUE TITLE
Add ignore-occluding-blocks to the list

### ISSUE THREAD

**Issue by YouHaveTrouble** [YouHaveTrouble/minecraft-optimization#70]
### Discussed in https://github.com/YouHaveTrouble/minecraft-optimization/discussions/69

<div type='discussions-op-text'>

<sup>Originally posted by **emielderckx** January 28, 2022</sup>
`ignore-occluding-blocks: true` should probably be added to the guide
https://paper.readthedocs.io/en/latest/server/configuration.html#hopper </div>

**Comment by Pantera07** [comment]
This already defaults to `ignore-occluding-blocks: true` in Pufferfish, Purpur.

**Comment by YouHaveTrouble** [comment]
> This already defaults to ignore-occluding-blocks: true in Pufferfish, Purpur.

it won't hurt to describe what it does and let users decide if they want to keep it on.

**Comment by YouHaveTrouble** [comment]
added in 4d76d693aa3406628fd44519f85faeda1bd44e9e
