### ISSUE TITLE
Purpur is not Pufferfish fork.

### ISSUE THREAD

**Issue by BrainRTP** [YouHaveTrouble/minecraft-optimization#75]
Purpur is Paper fork,  not Pufferfish

**Comment by YouHaveTrouble** [comment]
Pufferfish is indeed an upstream for Purpur, making Purpur a Pufferfish fork.

**Comment by BrainRTP** [comment]
<img width="843" alt="Снимок экрана 2022-03-22 в 11 34 04" src="https://user-images.githubusercontent.com/22731705/159421781-40ea22f5-068f-459d-b4aa-29e08c7b54c1.png">

This is what purpur says in the [description](https://github.com/PurpurMC/Purpur)
Does this mean that purpur is a fork of pufferfish rather than paper?

**Comment by emielderckx** [comment]
> <img alt="Снимок экрана 2022-03-22 в 11 34 04" width="843" src="https://user-images.githubusercontent.com/22731705/159421781-40ea22f5-068f-459d-b4aa-29e08c7b54c1.png">
> 
> This is what purpur says in the [description](https://github.com/PurpurMC/Purpur) Does this mean that purpur is a fork of pufferfish rather than paper?

Purpur is a feature-oriented fork that adds [many configuration options and features](https://purpurmc.org/docs) without the requirement of plugins, and includes our own bundle of performance patches.

[Purpur Patches](https://github.com/PurpurMC/Purpur/tree/master/patches)

Upstream patches:
- [Paper](https://github.com/PaperMC/Paper/tree/master/patches)
- [Pufferfish](https://github.com/pufferfish-gg/Pufferfish/tree/master/patches)

**Comment by YouHaveTrouble** [comment]
Don't necro 2 year old threads...

**Comment by seriousfreezing** [comment]
I only realized after I replied, lmao
