### ISSUE TITLE
Request for clarification.

### ISSUE THREAD

**Issue by Trevo525** [YouHaveTrouble/minecraft-optimization#76]
The following quote is taken from the guide right at the end of the [Mobs](https://github.com/YouHaveTrouble/minecraft-optimization#mobs) > [paper.yml](https://github.com/YouHaveTrouble/minecraft-optimization#paperyml-1) > [tick-rates](https://github.com/YouHaveTrouble/minecraft-optimization#tick-rates) section.

> It is not recommended to change these values from their defaults while [Pufferfish's DAB](https://github.com/YouHaveTrouble/minecraft-optimization#dab) is enabled!

What does this apply to? Is it saying the entire [Mobs](https://github.com/YouHaveTrouble/minecraft-optimization#mobs) configurations should stay default if DAB is turned on, the [paper.yml](https://github.com/YouHaveTrouble/minecraft-optimization#paperyml-1) section specifically, or just the [tick-rates](https://github.com/YouHaveTrouble/minecraft-optimization#tick-rates) in that section?

**Comment by YouHaveTrouble** [comment]
Just the tick rates, if that was for the whole section, it would be directly under that section's name :)
