### ISSUE TITLE
"remove-corrupt-tile-entities" option has been removed

### ISSUE THREAD

**Issue by Leeo97one** [YouHaveTrouble/minecraft-optimization#78]
Since build 241 of Paper (https://github.com/PaperMC/Paper/commit/ea1efef1164aa7653119eb4be000749930e5b4da#diff-93e368bf452ceaca8ba6d6d9c063395a89cbd8a44fda0cd57f64767102eed4aa).

**Comment by YouHaveTrouble** [comment]
I removed the setting from the guide. Thanks for pointing this out!
