### ISSUE TITLE
Include default files with optimized values

### ISSUE THREAD

**Issue by ArtelGG** [YouHaveTrouble/minecraft-optimization#82]
It would be extremely helpful if there was included files which contained all of the 'good starting values', so you could simply drag & drop into new (or existing) server instances and have the optimizations done and ready to go once the server starts. Missing keys are automatically added to the files so this shouldn't cause any issues.

**Comment by YouHaveTrouble** [comment]
I disagree. That would only end up with people copy-pasting existing files and not reading. That's not the point of the guide. Starting values are not magic values, they will not work for every server ever, they are what they're called - sane starting values for each option. To go further or less depends on the specific server and can't be generalized.
