### ISSUE TITLE
Question re: Suggested Optimizations for Fabric/Vanilla

### ISSUE THREAD

**Issue by johntdavis84** [YouHaveTrouble/minecraft-optimization#88]
Hello,

Thank you for putting together this excellent guide. I've run servers before, but I only found this last week; it's wonderful.

A friend asked me to put up a Fabric server for them, which I've never worked with before. I'm treating it like a vanilla server with an added mod pack API. To that end, I looked in the document here for adjustments specific to Vanilla and Fabric itself, and ignored the other server types. Is that the way to go?

**I ended up adjusting `sync chunk writes`, `network compression threshold`, and the `simulation` and `view` distances,** and otherwise leaving everything else alone for now. Everything else seemed to not apply, since I'm not running another server type. **Am I missing anything?**

**Comment by YouHaveTrouble** [comment]
The guide is focused on bukkitland, so yeah, the options in server.properties are only aplicable things for modded servers.
You can look for optimization mods like starlight or lithium and whatever you can find at [modrinth](https://modrinth.com/mods?f=categories%3Aoptimization&e=server)

**Comment by johntdavis84** [comment]
Awesome. I just wanted to make sure I wasn’t missing something obvious.

I’m on a pretty powerful little ARM SBC, with 3.5 GB of RAM allocated to the server (until I can get an idea of what it actually needs and dial it back). I’m getting server lag when the server starts, but I think that might just be the start up routines trying to go to fast. I need to actually use it for a while and see what happens.

Thanks again!

**Comment by emielderckx** [comment]
3.5 GB is pretty low for a modern Minecraft server, come join us on Discord if you want more advice: https://discord.gg/j8KK5dGBps

**Comment by johntdavis84** [comment]
I’m actually on the discord. Enjoying it so far. :)

This little ARM SBC only has 8 GB total, so I’m giving it nearly half the system RAM. This is just temporary until I can move the server onto the much more powerful virtualization host I’m building. At that point, I’ll give it at least 8 GB.
