### ISSUE TITLE
By defaults, do you mean the pre-generated defaults or the ones you suggest?

### ISSUE THREAD

**Issue by nickavem** [YouHaveTrouble/minecraft-optimization#89]
Please clarify what you mean [here](https://github.com/YouHaveTrouble/minecraft-optimization#tick-rates).

**Comment by YouHaveTrouble** [comment]
Do you mean "starting values"?

**Comment by nickavem** [comment]
Yes

**Comment by YouHaveTrouble** [comment]
Those are sane starting values you can start adjusting for your server.

**Comment by nickavem** [comment]
But you have a tag:
> It is not recommended to change these values from their defaults while [Pufferfish's DAB](https://github.com/YouHaveTrouble/minecraft-optimization#dabenabled) is enabled!

What do you mean by defaults?

**Comment by YouHaveTrouble** [comment]
The default values? That are generated with config?
What else defaults could mean?
